### ISSUE TITLE
Add 'copy link' to share options

### ISSUE THREAD

**Issue by tarnas14** [tarnas14/ti4-companion#11]
there's a "share" button when viewing a session
currently it opens a modal with QR code (see below)

desired behaviour: add a "copy link" with a nice button section below the qr code, which will put the link in clipboard

![1631572468749](https://user-images.githubusercontent.com/9142942/133165226-3ab50e53-b55e-4111-a5b4-bf32077f55d8.png)

**Comment by Ronald-patrick** [comment]
Hi, I wanted to work on this issue!

**Comment by tarnas14** [comment]
sure, go ahead :)

**Comment by Ronald-patrick** [comment]
![Capture3](https://user-images.githubusercontent.com/66828049/133250727-c5ac0bec-23ed-4186-8b27-7466da02ab91.JPG)
Getting this error !!

**Comment by Ronald-patrick** [comment]
@tarnas14

**Comment by tarnas14** [comment]
@Ronald-patrick sorry for the inconvenience

I think I know what's happening that I didn't experience myself:
I bet that if you go to [https://localhost:5001/api/objectives](https://localhost:5001/api/objectives) your browser will complain that it is not a secure location, so the request fails
if you tell the browser to trust that endpoint, the frontend application will work (because I bet that right now if you go to development tools and look at Network, you'll see the https://localhost:5001/api/objectives failed)

my browser already trusts localhost:5001 ^^ I'll make an issue and try to figure out a way to automate that trust OR will include a troubleshooting guide in the README

**Comment by Ronald-patrick** [comment]
Thanks its working now! I just need to click proceed in localhost 5000.

**Comment by Ronald-patrick** [comment]
If u want i can add the solution in readme !

**Comment by tarnas14** [comment]
if you run into anything or have any feedback, don't hesitate to write or create an issue explaining what additions or changes you'd like to see (or make a PR ;) )

**Comment by Ronald-patrick** [comment]
Thanks! This will be my first PR 😁 I am exploring Open source Contribution!

**Comment by Ronald-patrick** [comment]
Kindly review the PR @tarnas14  !
