### ISSUE TITLE
Allow removing games from the list

### ISSUE THREAD

**Issue by tarnas14** [tarnas14/ti4-companion#276]
allow removing a list from "your list" on the main page

**Comment by slawciu** [comment]
Delete button at the end of list item:
![image](https://user-images.githubusercontent.com/3041703/195146028-18ecf2f3-8f22-446c-983b-127649d92c48.png)

A couple of questions:

- Should the Delete button contain an icon of trash or something? Or just a text?
- When the delete button is in place this edit badge is a little bit misleading - it looks like a button as well! Maybe we can move it somewhere else?
- Should we check the password (if set) before deleting the session?
- Should there be any notification about deleted item?
- confirmation: type session name vs yes/no?

**Comment by slawciu** [comment]
![2022-10-11_19h51_50](https://user-images.githubusercontent.com/3041703/195165106-ed7451e6-15a7-4af4-bc6b-50d11aa062e7.gif)

This is how it looks when answers are like:
- Only Delete text
- Edit badge in place
- No password check
- No notification
- Yes/no confirmation

Windows. Hue.

**Comment by tarnas14** [comment]
yes/no is ok, I think you're right about the badge being misleading
maybe we should move it to the left and leave actions (delete for now) on the right?

**Comment by slawciu** [comment]
![image](https://user-images.githubusercontent.com/3041703/195902314-7abb32b1-5876-4270-9e21-2d1005efa8ba.png)
