### ISSUE TITLE
Missing/incorrect i18n label for togglePlastic tooltip

### ISSUE THREAD

**Issue by slawciu** [tarnas14/ti4-companion#284]
Content of tooltip is wrong.

![image](https://user-images.githubusercontent.com/3041703/194130240-f1999b06-6cd9-49c7-90e9-88efa0de93ef.png)

Content of `togglePlastic` in i18n data structure:
https://github.com/paxmagnifica/ti4-companion/blob/development/client/src/i18n/index.js#L315:
```
togglePlastic: {
              tooltip: 'toggle plastic colors',
              nowOn: 'now on',
              nowOff: 'now off',
            },
```

**Comment by KarolaB** [comment]
I'll take it :)
