### ISSUE TITLE
Close "share" modal after link is copied

### ISSUE THREAD

**Issue by tarnas14** [tarnas14/ti4-companion#291]
![Peek 2022-10-09 10-14](https://user-images.githubusercontent.com/9142942/194745600-5c9fab8d-ee63-402a-a3dc-745bef80a00c.gif)

when viewing the session, user can share the session link - via QR code or copying the link

current behaviour:
- when user clicks "copy link", the modal remains open

desired behaviour:
- modal closes after "copy link" is clicked and the link is in clipboard
- informational toast is shown that link is safe in the clipboard

**Comment by slawciu** [comment]
dibz!

**Comment by slawciu** [comment]
![2022-10-10_21h48_57](https://user-images.githubusercontent.com/3041703/194941984-f392c247-5d79-4e7f-997b-44094cfe65d1.gif)
