### ISSUE TITLE
Separate stage 1 / stage 2 and secret objectives in right slide in menu

### ISSUE THREAD

**Issue by fifak1313** [tarnas14/ti4-companion#32]

**Comment by tarnas14** [comment]
you mean have them as two different tabs instead of having all objectives in one place?

**Comment by fifak1313** [comment]
yep, 3 different tabs:
1stage
2stage
secret

**Comment by tarnas14** [comment]
I think we can do 3 different links, which will open the "objectives" with proper filters already on

**Comment by tarnas14** [comment]
trying

**Comment by tarnas14** [comment]
@fifak1313 

see the above

I left the ability to show all objectives in one place, because you might want to search through all of them
otherwise, clicking the "tab" shows only those objectives
